# Copyright(c) 2021 Cisco and / or its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

'''
Common utils for the load balancer testbed
'''
import logging
import sys
import os
import json
import subprocess

VERBOSE = False
LOOP_DIR = '/mnt/loop'
DIRNAME = os.path.dirname(__file__)

def init_logger(filename, logger_name):
    '''
    @brief:
        initialize logger that redirect info to a file just in case
        we lost connection to the notebook
    @params:
        filename: to which file should we log all the info
        logger_name: an alias to the logger
    '''

    # get current timestamp

    logging.basicConfig(
        level=logging.INFO,
        format='[%(asctime)s] %(name)s {%(filename)s:%(lineno)d} %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(filename=filename),
            logging.StreamHandler(sys.stdout)
        ]
    )

    # Test
    logger = logging.getLogger(logger_name)
    logger.info('### Init. Logger {:s} ###'.format(logger_name))

    return logger

def get_config(filename):
    '''
    load config file for all nodes (generated by ${root}/src/utils/gen_conf.py)
    Note: this should be the first function to call
    @params:
        filename
    '''
    conf_file = os.path.join(
        COMMON_CONF['dir']['root'], 'config', 'cluster', filename)
    if not os.path.isfile(conf_file):  # if config file doesn't exist
        print(
            'Config {} does not exist, create w/ default config.'.format(
                conf_file))
    return json_read_file(conf_file)

def json_write2file(data, filename):
    '''
    @brief:
        write data to json file
    '''
    with open(filename, "w") as file_target:
        # w/ indent the file looks better
        json.dump(data, file_target, indent=4)


def json_read_file(filename):
    '''
    @brief:
        read data from json file
    '''
    with open(filename, "r") as file_target:
        return json.load(file_target)


def write_file(lines, filename):
    '''
    @desc:
        write lines from a list of strings to a file
    @params:
        (str) filename
        (list[str]) lines
    '''
    with open(filename, "w") as file_target:
        for line_ in lines:
            file_target.write("{}\n".format(line_))


def create_folder(dirs):
    '''
    @brief:
        create folder if does not exist
    '''
    for dir_ in dirs:
        if not os.path.exists(dir_):
            os.mkdir(dir_)


def read_file(filename):
    '''
    @desc:   read lines from a file into a list
    @params: (str)filename
    @return: list of strings
    '''
    lines = []
    with open(filename, "r") as myfile:
        lines = [line.rstrip('\n') for line in myfile]
    return lines


def subprocess_cmd(command):
    '''
    execute command and print out result
    '''
    process = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
    proc_stdout = process.communicate()[0].strip()
    return proc_stdout.decode("utf-8")


def mount_image(img):
    '''
    mount image: img
    @param:
        img: image to be mounted
    @e.g.:
        mount_image(CONFIG['img']['base'])
        # then run `sudo chroot /mnt/loop/ /bin/bash` to check something like:
        # `apt list --installed | grep vpp`
    '''
    if VERBOSE:
        print(">> Mounting image: {}...".format(img), end='\r')
    cmd = "sudo modprobe nbd max_part=8;\
    sudo qemu-nbd --connect=/dev/nbd0 {};\
    sudo mount -o loop /dev/nbd0p1 {};\
    \n".format(img, LOOP_DIR)
    subprocess_cmd(cmd)
    if VERBOSE:
        print(">> Mounting image done!")


def umount_image():
    '''
    cleanup mounted image (umount and disconnect)
    '''
    if os.path.exists('{}/home/cisco'.format(LOOP_DIR)):
        if VERBOSE:
            print(">> Umounting image...")
        cmd = "sudo chown 1000:1000 {0}/home/cisco/*;\
        sudo umount {0}/;\
        sudo qemu-nbd --disconnect /dev/nbd0;\n".format(LOOP_DIR)
        subprocess_cmd(cmd)
        if VERBOSE:
            print(">> Umounting image done!")


DIRNAME_ = os.path.dirname(__file__)
# get common configuration
FILENAME_ = os.path.join(DIRNAME_, '../../config/global_conf.json')
COMMON_CONF = json_read_file(FILENAME_)
# get all LB methods
FILENAME_ = os.path.join(DIRNAME_, '../../config/lb-methods.json')
LB_METHODS = json_read_file(FILENAME_)
